#!/usr/bin/python
import os
 
virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from flaskweb import app as application
from LaBSKApi.statistics import Statistics
from LaBSKApi.MongoDB import MongoDB
from presenter.ReportStatsPresenter import ReportStatsPresenter
from LaBSKApi.reportstats import ReportStatsService
import flaskweb

# Setup

#MONGODB_URI = os.environ['OPENSHIFT_MONGODB_DB_HOST']+":"+os.environ['OPENSHIFT_MONGODB_DB_PORT']
#connection_url = "mongodb://" + MONGODB_URI + "/"
db = MongoDB(host = os.environ['OPENSHIFT_MONGODB_DB_HOST'],
             port = os.environ['OPENSHIFT_MONGODB_DB_PORT'],
             db= "phorumledge",
             col = "stats")
db.authenticate("admin","9UsXjxnQelHf")
stats = Statistics(db)
stats.add_ignore_ip("188.78.230.48") # My home laptop
stats.add_ignore_ip("10.85.78.172") # Every hour
stats.add_ignore_ip("194.179.68.63") # Every hour
flaskweb.set_stats_module(stats)
flaskweb.set_reportstats_module(ReportStatsPresenter(ReportStatsService(db)))

